command: ["npm", "run", "start", "--filter=@repo/backend"]

env:
  - name: ENCRYPTION_KEY
    valueFrom: encryption-key-secret
  - name: DATABASE_URL
    valueFrom: database-url-secret
  - name: WAREHOUSE_ID
    valueFrom: warehouse
